apiVersion: v1
kind: Namespace
metadata:
  name: tilt-integration
  labels:
    name: tilt-integration
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: tilt-integration
  labels:
    app: app
spec:
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: babel-node-base
          command: ["yarn", "production"]
          ports:
            - containerPort: 3000
          workingDir: /app
